### ISSUE TITLE
프로세스 가동시 weight 적용

### ISSUE THREAD

**Issue by djinchung** [fatima-go/juno#11]
**AS-IS**
a 프로세스는 b 프로세스가 정상적으로 올라와야 동작이 가능하다.
현재는 startro 등의 명령어로 전체 프로세스를 띄울때 
a,b,c,d,... 모든 프로세스를 동시에 시작하니까 이슈가 될 수 있다.

**TO-BE**
프로세스간 시작 순서 정의
1. 프로세스간 weight 를 명시
2. starting weight 로 우선순위를 명시한다

개인적인 생각엔 1번은 복잡성이 있을거 같아서 2번으로 진행하면 어떨까 싶다..

```yaml
process:
    - gid: 1
      name: jupiter
      loglevel: info
      weight: 1
      startsec: 10
```

`weight` 가 표시되지 않은 프로세스들은 기본값이 0 이다.
(위의 예시처럼) weight 로 프로세스의 start weight 를 명시한다.
여러 프로세스를 동시에 가동시킬때 weight 가 높은 프로세스들을 먼저 시작하고,
정상적으로 시작하면 이후에 다음 weight 높은 프로세스들을 시작하는 식으로 진행해본다.

`startsec` 의 경우 프로세스가 가동 후 온라인이 될때까지 충분히 보장되는 시간(초)을 의미한다.
기본값은 0이다. 
일부 프로세스는 프로세스 가동 후 (서비스 로직에 따라) 수초 후에 서비스 가능한 상태가 되기에 해당 옵션을 지원한다
