### ISSUE TITLE
goaway signal skip 방법  제공

### ISSUE THREAD

**Issue by djinchung** [fatima-go/juno#9]
**AS-IS**
golang fatima 패키지로 개발한 프로세스들은 rostop 등으로 프로세스 중지할때 이슈가 없다.
그런데 fatima 운영 패키지는 비단 golang fatima 패키지로 개발된 프로세스뿐만이 아니라 다양한 프로세스들(e.g java, python, ...)도 등록하여 모니터링하고 제어할 수 있다.
실제 3rd party java 프로세스(다우기술 dbro)이나 apache zookeeper (opensource)등도 등록하여 사용한다.
다만 이 경우 3rd party 프로세스가 fatima 패키지에서 프로세스를 내릴때(rostop) 전달하는 `SIGUSR1` 시그널을 받아서 흘려보내지 못 할 경우 프로그램이 블럭이 걸리기도 한다.
현재 프로세스 중지는 아래와 같은 흐름으로 진행된다.

1. SIGUSR1 전송 
2. goaway.sh 실행(존재할경우)
3. SIGTERM 전송

따라서 fatima 운영 패키지에 추가한 프로세스중에 rostop 명령어등으로 셧다운시 `SIGUSR1을 스킵`할 방안이 필요하다

**TO-BE**
아래는 파티마 패키지 프로세스 등록 예제이다
```yaml
# this is fatima-package.yaml sample
group: [{id: 1, name: OPM}, {id: 2, name: SVC}, {id: 3, name: GRPC}, {id: 4, name: WEB}, {id: 5, name: EVENT}]
process:
    - gid: 1
      name: juno
      loglevel: info
    - gid: 1
      name: saturn
      loglevel: info
    - gid: 2
      name: dbro
      loglevel: info
      sigstop: false
```

sigstop 은 default true 값으로 처리한다. 만약 이 값을 false 로 지정하면 rostop 명령어등으로 셧다운시 SIGUSR1 을 보내지 않도록 한다
